namespace vPinEventMonitor;

public static class PipeEventCodes
{
    public const int DmdFrame  = 1;  // 128*32 bytes, pixel intensities 0-100
    public const int Lamps     = 2;  // pairs: [lampId (byte), onOff (byte)], ...
    public const int Switches  = 3;  // pairs: [switchId (byte), onOff (byte)], ...
    public const int Solenoids = 4;  // pairs: [solenoidId (byte), onOff (byte)], ...
    public const int GIs       = 5;  // pairs: [giId (byte), brightness (byte 0-8)], ...
}
